"""Trigger and effect type constants.

Moved from engine/trigger_system.py.
"""

TRIGGER_TYPES = [
    "on_take",
    "on_drop",
    "on_examine",
    "on_inspect",
    "on_use",
    "on_use_progressive",
    "on_use_on",
    "on_look",
    "on_search",
    "on_tick",
    "on_eat",
    "on_drink",
    "on_read",
    "on_light",
    "on_activate",
    "on_equip",
    "on_unequip",
    "on_throw",
    "on_break",
    "on_depleted",
    "on_toggle_on",
    "on_toggle_off",
    "on_open",
    "on_close",
    "on_state_enter",
    "on_state_exit",
    "on_auto_open",
    "on_enter",
    "on_speech",
    "on_fail_jump",
    "on_fail_climb",
    "on_delayed",
    "on_spoil",
    # task-234: turn-cycle and time/moon triggers — fired by the engine on
    # area/way/character nodes (see VirtualWorldEngine._fire_turn_triggers /
    # _fire_time_triggers), not by item interaction.
    "on_turn_start",
    "on_turn_end",
    "on_dawn",
    "on_dusk",
    "on_day",
    "on_night",
    "on_full_moon",
    "on_blood_moon",
]

EFFECT_TYPES = [
    "destroy_self",
    "message",
    "damage",
    "save",
    "heal",
    "spawn_item",
    "spawn_character",
    "give_item",
    "remove_item",
    "consume_item",
    "set_state",
    "set_environment",
    "teleport",
    "rename",
    "unlock_way",
    "drain",
    "set_description",
    "append_description",
    "adjust_vital",
    # task-538: the two halves of "a maximum is data, not a constant" (task-537 §M).
    # `set_vital` sets the meter to an exact value; `modify_vital_max` moves the
    # ceiling everything else clamps against, which is what a trait or a
    # level-up effect needs.
    "set_vital",
    "modify_vital_max",
    "adjust_environment",
    "set_hidden",
    "adjust_uses",
    "end_scenario",
    "restart_scenario",
    "apply_condition",
    "remove_condition",
    "apply_trait",
    "remove_trait",
    "add_tag",
    "remove_tag",
    "set_parameter",
    "adjust_parameter",
    "grant_memory",
    "surface_memory",
    "suppress_memory",
    "unblock_memory",
    "schedule_trigger",
    "spawn_way",
    "spawn_area",
    "set_way_target",
    "set_way_view",
    "llm_respond",
    "scry",
    # task-227/234: weather/forecast GM + trigger controls.
    "set_time",
    "set_date",
    "set_weather",
    "forecast_override",
    "adjust_forecast",
    # task-233: dynamic area statuses.
    "apply_area_status",
    "clear_area_status",
    # task-231: wet/dry clothing state.
    "set_wet",
    # task-391: Lyrie's spellbook. Durations are in ticks.
    "polymorph_target",
    "create_illusory_companion",
    "broadcast_emotion",
    "bind_companion",
    "reveal_hidden",
]

# task-242: effects agents may bind via the `bind`/`enchant` action. This is
# the safe subset — no inventory mutations, no world-destroying effects.
SAFE_EFFECT_TYPES = {
    "message",
    "set_state",
    "adjust_uses",
    "set_environment",
    "adjust_environment",
    "set_parameter",
    "adjust_parameter",
    "apply_condition",
    "remove_condition",
    "apply_trait",
    "remove_trait",
    "add_tag",
    "remove_tag",
    "surface_memory",
    "suppress_memory",
    "append_description",
    "set_description",
    "adjust_vital",
    # task-538: same class as `adjust_vital` and `apply_trait`, both already
    # here — a charm that grants vitality is an ordinary authored reward, and a
    # maximum is just another stat once it is data.
    "set_vital",
    "modify_vital_max",
    "heal",
    "damage",
    "llm_respond",
}
