"""Trigger and effect type constants.

Moved from engine/trigger_system.py.
"""

TRIGGER_TYPES = [
    "on_take",
    "on_drop",
    "on_examine",
    "on_inspect",
    "on_use",
    "on_use_progressive",
    "on_use_on",
    "on_look",
    "on_search",
    "on_tick",
    "on_eat",
    "on_drink",
    "on_read",
    "on_light",
    "on_activate",
    "on_equip",
    "on_unequip",
    "on_throw",
    "on_break",
    "on_depleted",
    "on_toggle_on",
    "on_toggle_off",
    "on_open",
    "on_close",
    "on_state_enter",
    "on_state_exit",
    "on_auto_open",
    "on_enter",
    "on_speech",
    "on_fail_jump",
    "on_fail_climb",
    "on_delayed",
    "on_spoil",
]

EFFECT_TYPES = [
    "destroy_self",
    "message",
    "damage",
    "save",
    "heal",
    "spawn_item",
    "spawn_character",
    "give_item",
    "remove_item",
    "consume_item",
    "set_state",
    "set_environment",
    "teleport",
    "rename",
    "unlock_way",
    "drain",
    "set_description",
    "append_description",
    "adjust_vital",
    "adjust_environment",
    "set_hidden",
    "adjust_uses",
    "end_scenario",
    "restart_scenario",
    "apply_condition",
    "remove_condition",
    "apply_trait",
    "remove_trait",
    "add_tag",
    "remove_tag",
    "set_parameter",
    "adjust_parameter",
    "surface_memory",
    "suppress_memory",
    "unblock_memory",
    "schedule_trigger",
    "spawn_way",
    "spawn_area",
    "set_way_target",
    "set_way_view",
    "llm_respond",
    "scry",
]

# task-242: effects agents may bind via the `bind`/`enchant` action. This is
# the safe subset — no inventory mutations, no world-destroying effects.
SAFE_EFFECT_TYPES = {
    "message",
    "set_state",
    "adjust_uses",
    "set_environment",
    "adjust_environment",
    "set_parameter",
    "adjust_parameter",
    "apply_condition",
    "remove_condition",
    "apply_trait",
    "remove_trait",
    "add_tag",
    "remove_tag",
    "surface_memory",
    "suppress_memory",
    "append_description",
    "set_description",
    "adjust_vital",
    "heal",
    "damage",
    "llm_respond",
}
