#!/usr/bin/env python3
"""Generate the client-side mirror of the action-tier table (task-352).

The single source of truth for "what does a verb cost" is
``engine/action_tiers.py`` (the module docstring there is explicit that a second
copy would be the "two homes" bug this tree keeps producing). But the turn
prompt is assembled **client-side**: ``computeItemActions`` and
``buildAvailableActionsBlock`` render the per-object verb brackets and must drop
verbs the character can no longer pay for from its remaining ``turn_slots``.
That needs the tier table in the browser.

So this tool reads ``engine/action_tiers.py`` and emits a generated TypeScript
module, ``static/js/agent/action-tiers.ts`` (compiled to ``.js`` by
``npm run build:ts``). ``--check`` fails when the emitted file drifts from the
Python source, so the two homes stay one.

    python tools/action_tiers_index.py --write   # regenerate
    python tools/action_tiers_index.py --check   # fail on drift
"""

from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

OUT_REL = os.path.join("static", "js", "agent", "action-tiers.ts")


def _js_str(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _obj(mapping: dict, *, indent: str = "        ", sort: bool = True) -> str:
    keys = sorted(mapping) if sort else list(mapping)
    lines = []
    for key in keys:
        value = mapping[key]
        if isinstance(value, str):
            rendered = _js_str(value)
        else:
            rendered = str(value)
        lines.append(f"{indent}{_js_str(key)}: {rendered},")
    return "\n".join(lines)


def build_ts() -> str:
    from engine.action_tiers import DEFAULT_BUDGET, VALID_TIERS, VERB_TIERS
    from engine.equipment import INTRINSIC_ABILITY_TAGS

    verbs = _obj(VERB_TIERS)
    budget = _obj(DEFAULT_BUDGET, sort=False)
    valid = "\n".join(f"        {_js_str(t)}," for t in sorted(VALID_TIERS))
    tags = "\n".join(f"        {_js_str(t)}," for t in sorted(INTRINSIC_ABILITY_TAGS))

    return f"""/**
 * action-tiers.generated — client mirror of engine/action_tiers.py (task-352).
 *
 * GENERATED by tools/action_tiers_index.py --write. DO NOT EDIT BY HAND.
 * Single source of truth: engine/action_tiers.py; `tools/action_tiers_index.py
 * --check` fails when this file drifts from it. The browser needs the tier
 * table to drop verbs a character can no longer pay for from its remaining
 * turn_slots when the turn prompt is rendered — the hide is guidance only, the
 * engine's _slot_gate is the enforcement.
 *
 * @module agent/action-tiers — client mirror of the engine's free/minor/major/activity table
 * @contributes ActionTiers: VERB_TIERS, DEFAULT_BUDGET, VALID_TIERS, tierOf, canPay, canAfford
 * @powers the turn prompt — dropping brackets and available actions the remaining turn_slots cannot pay for
 * @relates mirrors engine/action_tiers.py; checked by tools/action_tiers_index.py --check
 * @docs docs/virtualWorld/Gameplay/Turn Queue & Human Turns.md
 */

(window as unknown as {{ ActionTiers: unknown }}).ActionTiers = (() => {{
    'use strict';

    const VALID_TIERS: string[] = [
{valid}
    ];

    const DEFAULT_BUDGET: Record<string, number> = {{
{budget}
    }};

    const VERB_TIERS: Record<string, string> = {{
{verbs}
    }};

    const INTRINSIC_ABILITY_TAGS: string[] = [
{tags}
    ];

    /** Ascending by value: a higher slot may pay for a lower action. */
    const TIER_ORDER = ['free', 'minor', 'major'];

    /** True when *tags* mark a node as an intrinsic ability (spell/talent/power). */
    function isIntrinsic(props: Record<string, unknown> | null | undefined): boolean {{
        const raw = (props || {{}}).tags;
        const tags = (Array.isArray(raw) ? raw : String(raw ?? '').split(','))
            .map((t) => String(t).trim().toLowerCase())
            .filter(Boolean);
        return INTRINSIC_ABILITY_TAGS.some((t) => tags.includes(t));
    }}

    /**
     * The tier a verb costs for a given item, mirroring engine/action_tiers.py
     * `tier_of`: per-item `action_costs[verb].tier` override, then the
     * intrinsic-ability default of `minor`, then the table, then `major`.
     */
    function tierOf(verb: string, props: Record<string, unknown> | null | undefined): string {{
        const v = String(verb || '').trim().toLowerCase();
        const p = props || {{}};
        const override = ((p.action_costs as Record<string, {{ tier?: string }}>) || {{}})[v] || {{}};
        const declared = override.tier;
        if (declared && VALID_TIERS.includes(declared)) return declared;
        if (isIntrinsic(p)) return 'minor';
        return VERB_TIERS[v] || 'major';
    }}

    /**
     * True when the remaining *slots* can pay for an action of *tier*.
     * Mirrors engine/action_tiers.py `spend_slot`: the cheapest sufficient slot
     * wins, and a higher slot pays for a lower action (a major pays for an
     * `approach`). `activity` is its own slot and does not downgrade.
     */
    function canPay(slots: Record<string, number> | null | undefined, tier: string): boolean {{
        const s = slots || {{}};
        let t = String(tier || 'major');
        if (!VALID_TIERS.includes(t)) t = 'major';
        if (t === 'activity') return (s.activity || 0) > 0;
        const from = TIER_ORDER.indexOf(t);
        for (let i = from; i < TIER_ORDER.length; i += 1) {{
            if ((s[TIER_ORDER[i]] || 0) > 0) return true;
        }}
        return false;
    }}

    /** Convenience: can the character afford *verb* on *props* right now? */
    function canAfford(verb: string, props: Record<string, unknown> | null | undefined, slots: Record<string, number> | null | undefined): boolean {{
        if (!slots) return true; // no budget published: never hide (older saves)
        return canPay(slots, tierOf(verb, props));
    }}

    return {{ VERB_TIERS, DEFAULT_BUDGET, VALID_TIERS, tierOf, canPay, canAfford }};
}})();
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate the client mirror")
    group.add_argument("--check", action="store_true", help="fail if the mirror has drifted")
    args = parser.parse_args()

    out_path = os.path.join(ROOT, OUT_REL)
    expected = build_ts()

    if args.write:
        with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(expected)
        print(f"wrote {OUT_REL}")
        return 0

    try:
        with open(out_path, "r", encoding="utf-8") as fh:
            actual = fh.read()
    except FileNotFoundError:
        print(f"FAIL: {OUT_REL} is missing — run tools/action_tiers_index.py --write")
        return 1

    if actual != expected:
        print(f"FAIL: {OUT_REL} has drifted from engine/action_tiers.py")
        print("      run: python tools/action_tiers_index.py --write")
        return 1

    print(f"OK: {OUT_REL} matches engine/action_tiers.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
