#!/usr/bin/env python3
"""Generate (and guard) the front-end module index.

Every non-vendor module under ``static/js`` is expected to open with a leading
comment block carrying this contract:

    /**
     * @module <name> — <one-line purpose>
     * @contributes <what state/behaviour it owns>
     * @powers <user-facing feature(s) it enables>
     * @relates <depends on / used by>
     * @docs <docs path or 'none'>
     */

Usage:
    python tools/js_module_index.py --write            # regenerate the index
    python tools/js_module_index.py --update-baseline  # accept today's uncovered files
    python tools/js_module_index.py --check            # fail if a NEW file lacks the contract

The baseline exists so the ~110 not-yet-documented files don't block the guard;
new modules are held to the contract from day one.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path("static/js")
SKIP_DIRS = {"vendor", "node_modules"}
INDEX_PATH = Path("docs/design/js-module-index.md")
BASELINE_PATH = Path("docs/design/js-module-baseline.txt")

TAGS = ("module", "contributes", "powers", "relates", "docs")
TAG_RE = re.compile(r"^\s*\*?\s*@(" + "|".join(TAGS) + r")\s+(.*)$")


def _leading_block(text: str, limit: int = 60) -> str:
    """Return the leading comment block (or '') from the first *limit* lines."""
    out = []
    in_block = False
    for line in text.splitlines()[:limit]:
        s = line.strip()
        if not in_block:
            # A TypeScript-emitted script may start with a directive, e.g.
            # "use strict"; — step over it to reach the documentation block.
            if s in ('"use strict";', "'use strict';"):
                continue
            if s.startswith(("/*", "//", "/**")):
                in_block = True
            else:
                break
        out.append(line)
        if in_block and s.endswith("*/") and not s.startswith("//"):
            break
    return "\n".join(out)


def parse(path: Path):
    text = path.read_text(encoding="utf-8", errors="replace")
    block = _leading_block(text)
    meta = {}
    for line in block.splitlines():
        m = TAG_RE.match(line)
        if m:
            meta.setdefault(m.group(1), m.group(2).strip())
    return meta


def collect():
    entries = []
    for path in sorted(ROOT.rglob("*.js")):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        entries.append((path, parse(path)))
    return entries


def uncovered(entries):
    return [str(p).replace("\\", "/") for p, meta in entries
            if not meta.get("module") or not meta.get("contributes")]


def write_index(entries):
    covered = [(p, m) for p, m in entries if m.get("module") and m.get("contributes")]
    gaps = [(p, m) for p, m in entries if not (m.get("module") and m.get("contributes"))]

    lines = [
        "# Front-end module index",
        "",
        "Generated by `tools/js_module_index.py` — do not hand-edit.",
        "Each row is the module's own `@module` / `@contributes` / `@powers` contract.",
        "",
        f"- Modules scanned: **{len(entries)}**",
        f"- Documented: **{len(covered)}**",
        f"- Awaiting a contract header: **{len(gaps)}**",
        "",
        "## Documented modules",
        "",
        "| Module | Purpose | File | Contributes | Powers | Docs |",
        "|---|---|---|---|---|---|",
    ]
    for path, meta in covered:
        rel = str(path).replace("\\", "/")

        def cell(key):
            return (meta.get(key) or "").replace("|", "\\|")

        module_value = cell("module")
        for sep in ("\u2014", "\u2013"):
            if sep in module_value:
                name, _, purpose = module_value.partition(sep)
                break
        else:
            name, purpose = module_value, ""
        lines.append(
            f"| `{name.strip()}` | {purpose.strip()} | `{rel}` | {cell('contributes')} | "
            f"{cell('powers')} | {cell('docs')} |"
        )

    lines += ["", "## Awaiting a contract header", "",
              "These predate the contract; the guard ignores them until they are documented.", ""]
    for path, _ in gaps:
        lines.append(f"- `{str(path).replace(chr(92), '/')}`")
    lines.append("")

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"{INDEX_PATH}: {len(covered)} documented, {len(gaps)} awaiting.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the index")
    parser.add_argument("--check", action="store_true", help="fail on new uncovered modules")
    parser.add_argument("--update-baseline", action="store_true", help="record the uncovered list")
    args = parser.parse_args()

    entries = collect()
    gaps = uncovered(entries)

    if args.update_baseline:
        BASELINE_PATH.parent.mkdir(parents=True, exist_ok=True)
        BASELINE_PATH.write_text("\n".join(gaps) + "\n", encoding="utf-8")
        print(f"{BASELINE_PATH}: recorded {len(gaps)} uncovered module(s).")
    if args.write or not (args.check or args.update_baseline):
        write_index(entries)

    if args.check:
        if not BASELINE_PATH.exists():
            print(f"{BASELINE_PATH} missing — run --update-baseline once.")
            return 2
        known = set(BASELINE_PATH.read_text(encoding="utf-8").split())
        new_gaps = [g for g in gaps if g not in known]
        if new_gaps:
            print("New modules missing the @module/@contributes contract:")
            for g in new_gaps:
                print("  -", g)
            return 1
        print(f"Contract check OK ({len(gaps)} known-uncovered, no new gaps).")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
