#!/usr/bin/env python3
"""Summarise every scenario in ``data/scenarios``.

Reports, per file: size, graph node counts **by type**, edge/player counts, the
denormalized mirrors (``areas``/``rooms``/``ways``/``item_registry``), the
time model, and a short theme hint from ``world_lore``. Handy for the Scenario
Catalogue doc and for spotting degenerate/legacy files.

Usage::

    python tools/scenario_stats.py            # markdown table
    python tools/scenario_stats.py --json     # machine-readable
    python tools/scenario_stats.py --out /tmp/scenario-stats.md

The curated ``docs/virtualWorld/Scenario Catalogue.md`` is NOT generated by this
tool (its theme/status column is hand-written); compare against it, don't
``--out`` over it.
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCENARIOS_DIR = ROOT / "data" / "scenarios"

# Display order for the per-type columns.
TYPE_ORDER = ["area", "way", "item", "character", "player", "trigger",
              "recipe", "container", "door", "logic_trigger"]

# Files that are infrastructure, not authored scenarios.
SPECIAL = {"world_template.json": "template",
           "autosave.json": "live-world dump"}


def _lore_text(entry) -> str:
    """A one-line theme hint from a ``world_lore`` entry (str or dict)."""
    if isinstance(entry, dict):
        text = entry.get("title") or entry.get("content") or ""
        category = entry.get("category")
        text = str(text)
        return f"[{category}] {text[:130]}" if category else text[:140]
    return str(entry)[:140]


def summarise(path: Path) -> dict:
    rec: dict = {"file": path.name, "size_kb": round(path.stat().st_size / 1024, 1)}
    rec["kind"] = SPECIAL.get(path.name, "scenario")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:                                    # noqa: BLE001
        rec["error"] = f"{type(exc).__name__}: {exc}"
        return rec
    if not isinstance(data, dict):
        rec["error"] = "top-level JSON is not an object"
        return rec

    rec["name"] = (data.get("name") or data.get("title")
                   or data.get("scenario_name") or path.stem)
    graph = data.get("graph") if isinstance(data.get("graph"), dict) else {}
    nodes = graph.get("nodes") if isinstance(graph.get("nodes"), dict) else {}
    edges = graph.get("edges") if isinstance(graph.get("edges"), list) else []

    types: collections.Counter = collections.Counter()
    for node in nodes.values():
        if isinstance(node, dict):
            types[str(node.get("type") or "?")] += 1

    rec["nodes"] = len(nodes)
    rec["node_types"] = dict(sorted(types.items()))
    rec["edges"] = len(edges)
    players = data.get("players")
    rec["players"] = len(players) if isinstance(players, dict) else 0
    for mirror in ("areas", "rooms", "ways", "item_registry"):
        val = data.get(mirror)
        rec[f"mirror_{mirror}"] = len(val) if isinstance(val, (dict, list)) else 0

    lore = data.get("world_lore")
    if isinstance(lore, list):
        rec["lore"] = [_lore_text(x) for x in lore[:3]]
    elif lore:
        rec["lore"] = [_lore_text(lore)]
    else:
        rec["lore"] = []

    rec["active_player"] = data.get("active_player")
    rec["time_per_tick_minutes"] = data.get("time_per_tick_minutes")
    rec["clock_start"] = [data.get("clock_start_hour"), data.get("clock_start_minute")]
    rec["turn_number"] = data.get("turn_number")
    rec["time_ticks"] = data.get("time_ticks")
    rec["has_graph"] = bool(nodes)
    rec["legacy_schema"] = not bool(nodes)
    return rec


def collect() -> list:
    if not SCENARIOS_DIR.is_dir():
        print(f"no scenarios dir: {SCENARIOS_DIR}", file=sys.stderr)
        return []
    return [summarise(p) for p in sorted(SCENARIOS_DIR.glob("*.json"))]


def _types_cell(rec: dict) -> str:
    nt = rec.get("node_types") or {}
    if not nt:
        return "-"
    keys = [t for t in TYPE_ORDER if t in nt]
    keys += [t for t in nt if t not in keys]
    return ", ".join(f"{t}:{nt[t]}" for t in keys)


def markdown(records: list) -> str:
    cols = ["File", "Kind", "Name", "KB", "Nodes", "Edges", "Players",
            "Nodes by type", "Theme (world_lore[0])"]
    lines = ["| " + " | ".join(cols) + " |",
             "|" + "|".join("---" for _ in cols) + "|"]
    node_total: collections.Counter = collections.Counter()
    for rec in records:
        if rec.get("error"):
            lines.append(f"| {rec['file']} | {rec.get('kind','')} |  | "
                         f"{rec.get('size_kb','')} |  |  |  | ! {rec['error']} |  |")
            continue
        for t, n in (rec.get("node_types") or {}).items():
            node_total[t] += n
        theme = (rec.get("lore") or [""])[0].replace("|", "/")
        lines.append("| {file} | {kind} | {name} | {kb} | {nodes} | {edges} | "
                     "{players} | {types} | {theme} |".format(
                         file=rec["file"], kind=rec.get("kind", ""),
                         name=rec.get("name", ""), kb=rec.get("size_kb", ""),
                         nodes=rec.get("nodes", 0), edges=rec.get("edges", 0),
                         players=rec.get("players", 0),
                         types=_types_cell(rec), theme=theme))
    lines.append("")
    lines.append("**Totals across files:** "
                 + ", ".join(f"{t}={node_total[t]}" for t in sorted(node_total))
                 + f"; nodes={sum(node_total.values())}")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", action="store_true", help="emit raw JSON")
    ap.add_argument("--out", metavar="PATH", help="write the markdown to PATH")
    args = ap.parse_args()

    records = collect()
    if args.json:
        print(json.dumps(records, indent=2))
        return 0

    text = markdown(records)
    if args.out:
        Path(args.out).write_text(text + "\n", encoding="utf-8")
        print(f"wrote {args.out} ({len(records)} files)")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
