#!/usr/bin/env python3
"""Generate (and guard) the way-property reference.

`tools/way_properties.py` declares every property a way node carries, its axis, and
who reads it. This renders that into a documentation page and, with --check, fails when
any hand-maintained property list in the engine has drifted from it.

The drift is not hypothetical: five lists of this same set exist and they already
disagree. `insulation` is settable by a trigger and unreachable from the library;
`sound_barrier`, `jump_dc` and `climb_dc` are honoured by movement but appear in no
spawn list, so a trigger-spawned way silently loses them.

Usage:
    python tools/way_property_index.py --write    # regenerate the page
    python tools/way_property_index.py --check    # fail on drift
    python tools/way_property_index.py --report   # per-list coverage, for filling gaps
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from way_properties import AXES, PROPERTIES, SPAWN_LISTS  # noqa: E402

PAGE = Path("docs/virtualWorld/World Building/Way Properties.md")
BASELINE_PATH = Path("docs/virtualWorld/World Building/way-property-baseline.txt")

#: Keys the engine reads but which are structural rather than per-way authored, so their
#: absence from a spawn list is not drift.
NOT_A_SPAWN_KEY = {
    "area_from", "area_to", "current_state_seen", "see_through_seen",
    # read off the character, not the way
    "size",
    # connection-edge properties, not way-node properties
    "cardinal", "visible_in_direction", "direction", "reverse_direction",
}


def _tuple_after(text: str, anchor: str) -> list:
    """The quoted keys of the first tuple/list literal starting on a line *after* `anchor`.

    A literal opening on the anchor's own line does not count: the anchor names a
    statement, and we want the assignment it introduces.
    """
    anchor_line = text.find(anchor)
    if anchor_line < 0:
        return []
    anchor_lineno = text[:anchor_line].count("\n")
    tree = ast.parse(text)
    best = None
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Tuple, ast.List, ast.Set)) or not node.elts:
            continue
        if node.lineno <= anchor_lineno + 1:
            continue
        keys = [e.value for e in node.elts
                if isinstance(e, ast.Constant) and isinstance(e.value, str)]
        # A property list is short snake_case keys only. This rejects neighbouring
        # literals like ("way", "registry", ...) and the registry name tuples.
        if not keys or not all(re.fullmatch(r"[a-z_]{3,}", k) for k in keys):
            continue
        if best is None or node.lineno < best.lineno:
            best = node
    if best is None:
        return []
    return [e.value for e in best.elts
            if isinstance(e, ast.Constant) and isinstance(e.value, str)]


def collect_lists() -> dict:
    """label -> set of keys, for each hand-maintained list in the engine."""
    found = {}
    cache = {}
    for label, rel, start, end, must in SPAWN_LISTS:
        if rel not in cache:
            p = Path(rel)
            cache[rel] = p.read_text(encoding="utf-8", errors="replace") if p.exists() else ""
        text = cache[rel]
        keys = set()
        # `start` may occur several times; take the occurrence whose region satisfies
        # `must` when one is given.
        at = text.find(start)
        while at >= 0:
            stop = text.find(end, at + len(start))
            region = text[at:stop] if stop > at else ""
            if region and (must is None or must in region):
                # Both quote styles: the hand-maintained lists are inconsistent about it,
                # which is most of the reason this file exists.
                for literal in re.findall(r"""['"]([a-z_]{3,})['"]""", region):
                    keys.add(literal)
                break
            at = text.find(start, at + 1)
        found[label] = keys
    return found


def build_page() -> str:
    lists = collect_lists()
    out = []
    a = out.append

    a("# Way Properties")
    a("")
    a("<!-- GENERATED by tools/way_property_index.py --write. DO NOT EDIT BY HAND. -->")
    a("<!-- Source of truth: tools/way_properties.py. Run --check to verify the engine -->")
    a("<!-- has not drifted from it. -->")
    a("")
    a("Every property a `way` node can carry, what it decides, and which code reads it.")
    a("A way has no single *kind*: its meaning is a point on four independent traversal")
    a("axes, plus metadata that has none. Most surprising doors are an unusual")
    a("combination of ordinary values, not a new value anywhere.")
    a("")
    a("## The four traversal axes")
    a("")
    a("These are independent of each other. Any combination is valid, which is why")
    a("`see_through` is not a kind of door — it is one axis among four.")
    a("")
    for axis in ("passage", "transparency", "verb", "size"):
        a(f"- **{axis}** — {AXES[axis]}")
    a("")
    a("Everything else in this page is either naming and layout (`identity`) or editor")
    a("metadata (`authoring`), neither of which changes what a character can do.")
    a("")
    a("## Reading a way")
    a("")
    a("```")
    a("current_state   does NOT let you through unless it is open")
    a("see_through    does NOT let you through, and does NOT stop light or sight")
    a("requires       which verb the passage demands (crawl / climb / jump)")
    a("max_size       who fits, relative to the character's size")
    a("```")
    a("")
    a("Note that `movement.py` gates passage on `current_state` alone and never reads")
    a("`see_through`, while `barriers.py` resolves light and sound from `see_through`")
    a("*ahead of* `current_state`. That asymmetry is deliberate and is why a shut window")
    a("still lets light and sight through.")
    a("")
    a("The combinations that come up most:")
    a("")
    a("| what you want | how to say it |")
    a("|---|---|")
    a("| an open door | `current_state: open` |")
    a("| a door you can shut | `current_state: closed` |")
    a("| a window | `current_state: closed` + `see_through: true` |")
    a("| a glass door | `current_state: open` + `see_through: true` |")
    a("| an archway or trail you cannot shut | `open` + `prevent_close: true` |")
    a("| a glazed wall you must break | `closed` + `see_through: true` + `needs_open` |")
    a("| a crawlspace | `requires: crawl`, or `max_size` one tier under the character |")
    a("")

    for axis in AXES:
        rows = [p for p in PROPERTIES if p.axis == axis]
        if not rows:
            continue
        a(f"## {axis.capitalize()}")
        a("")
        a(f"_{AXES[axis]}._")
        a("")
        a("| property | values | notes |")
        a("|---|---|---|")
        for p in rows:
            vals = ", ".join(f"`{v}`" for v in p.values) if p.values else "—"
            note = p.notes.replace("|", "\\|") if p.notes else ""
            a(f"| `{p.name}` | {vals} | {note} |")
        a("")
        readers = [(p, p.reads) for p in rows if p.reads]
        if readers:
            a("### Read by")
            a("")
            for p, reads in readers:
                for path, line, what in reads:
                    a(f"- `{p.name}` — `{path}:{line}` — {what}")
            a("")

    # ── the coverage table that exists to make drift visible ────────────────────
    a("## Where each property is honored")
    a("")
    a("The engine copies this property list by hand in three library-facing places. A")
    a("blank cell means the list does not carry that key. They now agree: this table")
    a("used to show `insulation`, `sound_barrier`, `climb_dc`, `jump_dc`,")
    a("`refusal_message`, `blocked_description`, `cost` and `aliases` silently dropped on")
    a("library spawn and refresh while a hand-authored save kept them (task-659).")
    a("")
    names = [p.name for p in PROPERTIES if p.name not in NOT_A_SPAWN_KEY]
    header = "| property | " + " | ".join(entry[0] for entry in SPAWN_LISTS) + " |"
    a(header)
    a("|---" * (len(SPAWN_LISTS) + 1) + "|")
    for n in names:
        cells = []
        for label, _r, _s, _e, _m in SPAWN_LISTS:
            cells.append("yes" if n in lists.get(label, set()) else "—")
        a(f"| `{n}` | " + " | ".join(cells) + " |")
    a("")

    caveats = [(p, p.caveat) for p in PROPERTIES if p.caveat]
    if caveats:
        a("## Known gaps")
        a("")
        a("Declared or consumed somewhere, but not honored everywhere. Each needs a")
        a("decision, not just a note.")
        a("")
        for p, cav in caveats:
            a(f"- **`{p.name}`** — {cav}")
        a("")

    from way_properties import TRIGGER_OMISSIONS
    a("## The trigger spawn path is narrower")
    a("")
    a("`engine/effect_handlers/ways.py` carries only 7 keys, because it assigns the rest")
    a("in its own props dict above the copy tuple. The checker does not hold it to the")
    a("same set, but these are read by the engine and are still unreachable there:")
    a("")
    a("`" + "`, `".join(TRIGGER_OMISSIONS) + "`")
    a("")
    a("Widening it is a feature decision rather than a drift fix.")
    a("")

    a("## Where the compiler decides for you")
    a("")
    a("A way the WorldPainter compiles is not authored by hand, so three behaviours come")
    a("from the grid rather than from a property.")
    a("")
    a("- **Verticality is inferred, never declared.** `_climb_step`")
    a("  (`engine/world_compile.py`) turns a `floor` step over `DEFAULT_MAX_STOREY_STEP`")
    a("  (3, per-scope overridable) into a gated climb you cannot walk until a road is")
    a("  painted over it. A painted cell cannot declare \"this is a climb\". An interior")
    a("  opts out of the gate entirely by being an interior.")
    a("- **`CLIFF_FLOOR_DELTA` (2) is prose only** and `DEFAULT_MAX_STOREY_STEP` (3) is")
    a("  traversal. Adjacent constants, different jobs.")
    a("- **`_mint_way` hardcodes `see_through: True`**, so every painted door is glazed.")
    a("")
    return "\n".join(out) + "\n"


def drift() -> list:
    """Real differences between the declaration and the guarded lists.

    Only properties that declare an `expect` for a given list are checked against it, so
    a view-layer property or one a handler assigns directly never registers as drift.
    The unknown-key direction is always checked: a key in a list that the declaration
    does not know about is a property nobody documented.
    """
    lists = collect_lists()
    known = {p.name for p in PROPERTIES}
    problems = []
    for label, _r, _s, _e, _m in SPAWN_LISTS:
        keys = lists.get(label, set())
        unknown = sorted(k for k in keys if k not in known)
        missing = sorted(p.name for p in PROPERTIES
                         if label in p.expect and p.name not in keys)
        if unknown:
            problems.append(f"{label}: carries keys not declared in "
                            f"tools/way_properties.py -> {', '.join(unknown)}")
        if missing:
            problems.append(f"{label}: omits {len(missing)} declared "
                            f"properties -> {', '.join(missing)}")
    return problems


def write_baseline() -> int:
    BASELINE_PATH.parent.mkdir(parents=True, exist_ok=True)
    BASELINE_PATH.write_text("\n".join(drift()) + ("\n" if drift() else ""),
                             encoding="utf-8")
    print(f"wrote {BASELINE_PATH} ({len(drift())} known drift entries)")
    return 0


def check() -> int:
    """Fail only on drift *beyond* the recorded baseline.

    The drift recorded today is real and mostly pre-existing, so a gate that failed on
    a clean tree would just be a gate nobody runs. Same shape as
    tools/js_module_index.py: baseline the present, hold new work to the contract.
    """
    current = drift()
    baseline = []
    if BASELINE_PATH.exists():
        baseline = [ln for ln in BASELINE_PATH.read_text(encoding="utf-8")
                    .splitlines() if ln.strip()]
    new = [p for p in current if p not in baseline]
    fixed = [p for p in baseline if p not in current]
    if fixed:
        print(f"way-property index: {len(fixed)} baseline entr(y/ies) now resolved "
              f"— re-run --update-baseline to drop them")
    if new:
        print(f"way-property index: {len(new)} NEW drift problem(s)\n")
        for p in new:
            print(f"  - {p}")
        print("\nEither fix the engine list, or add the key to tools/way_properties.py "
              "if the engine is right and the declaration is behind.")
        return 1
    print(f"way-property index: {len(PROPERTIES)} properties, "
          f"{len(baseline)} baselined drift entr(ies), nothing new")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--update-baseline", action="store_true")
    args = ap.parse_args()

    if args.write:
        PAGE.parent.mkdir(parents=True, exist_ok=True)
        PAGE.write_text(build_page(), encoding="utf-8")
        print(f"wrote {PAGE}")
        return 0

    if args.update_baseline:
        return write_baseline()

    if args.check:
        return check()

    if args.report:
        lists = collect_lists()
        for label, _r, _s, _e, _m in SPAWN_LISTS:
            print(f"{label} ({len(lists.get(label, set()))} keys)")
            print("    " + ", ".join(sorted(lists.get(label, set()))))
        print()
        print(f"declared: {len(PROPERTIES)} properties")
        for problem in drift():
            print("  ! " + problem)
        return 0

    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())