"""Generate `interface Window` members from evidence in the codebase.

The bug this exists to prevent: `Window` had no members, so `window.config`
did not typecheck, so converters "fixed" it by deleting the `window.` prefix —
turning an undefined-safe guard into a ReferenceError. Completing `Window`
removes the temptation: the correct spelling becomes the spelling that compiles.

CRITICAL HONESTY RULE. Only names a module actually assigns via `window.X =`
belong on `Window`. A name that is only a lexical top-level `const`
(`const events = new EventBus()`) is NOT on window at runtime, so declaring it
would make `window.events` typecheck while being `undefined` — swapping one
silent trap for a worse one. Those names stay bare `declare const` and are
listed separately so the difference is visible rather than assumed.

Usage:
    python tools/window_members.py            # report
    python tools/window_members.py --write    # rewrite the Window block
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
JS_ROOT = REPO_ROOT / "static" / "js"
GLOBALS_DTS = JS_ROOT / "types" / "globals.d.ts"

START = "// >>> window members - generated by tools/window_members.py, do not hand-edit >>>"
END = "// <<< window members <<<"

WINDOW_ASSIGN = re.compile(r"\bwindow\.([A-Za-z_$][\w$]*)\s*=[^=]")
BARE_TOPLEVEL = re.compile(r"^(?:const|let|var|class|function)\s+([A-Za-z_$][\w$]*)", re.M)
DECLARED = re.compile(r"^declare const ([A-Za-z_$][\w$]*)", re.M)


def main() -> int:
    if not GLOBALS_DTS.exists():
        sys.exit(f"error: {GLOBALS_DTS} not found")

    assigned: dict[str, set[str]] = {}
    lexical: dict[str, set[str]] = {}

    for path in sorted(JS_ROOT.rglob("*.js")):
        if "vendor" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        rel = path.relative_to(REPO_ROOT).as_posix()
        for name in set(WINDOW_ASSIGN.findall(text)):
            assigned.setdefault(name, set()).add(rel)
        for name in set(BARE_TOPLEVEL.findall(text)):
            lexical.setdefault(name, set()).add(rel)

    declared = set(DECLARED.findall(GLOBALS_DTS.read_text(encoding="utf-8")))
    existing = set(re.findall(r"^\s{4}([A-Za-z_$][\w$]*)\??:", GLOBALS_DTS.read_text(encoding="utf-8"),
                              re.MULTILINE))

    on_window = sorted(n for n in assigned if n not in existing)
    both = sorted(n for n in assigned if n in lexical)
    lexical_only = sorted(n for n in declared if n in lexical and n not in assigned)

    print(f"names assigned via `window.X =`   : {len(assigned)}")
    print(f"  already on interface Window     : {len(assigned) - len(on_window)}")
    print(f"  NEW members to add              : {len(on_window)}")
    print(f"names that are lexical-only (NOT on window, keep bare): {len(lexical_only)}")
    print(f"names that are BOTH window-assigned and lexical       : {len(both)}")
    for name in both:
        print(f"    ! {name}  (window:{sorted(assigned[name])[0]}  lexical:{sorted(lexical[name])[0]})")

    if "--write" not in sys.argv:
        print("\nnew members:")
        for name in on_window:
            print(f"    {name}")
        print("\ndry run. Pass --write to regenerate the Window block.")
        return 0

    lines = [
        START,
        "// Generated by tools/window_members.py — do not hand-edit.",
        "//",
        "// Only names a module assigns via `window.X =` belong here: that is what",
        "// makes `window.X` a real, undefined-safe property access. Names that are",
        "// lexical top-level `const` are deliberately absent, because `window.X`",
        "// would typecheck for them while being `undefined` at runtime.",
        "//",
        "// WHY `any` AND NOT `unknown`: the whole point of this interface is to make",
        "// `window.config.maxTokens` COMPILE. With `unknown` every property access",
        "// through a window member errors, the converter is tempted to drop the",
        "// `window.` prefix again, and we are back to ReferenceError land. `any`",
        "// keeps the guard intact. Behaviour-correctness beats strictness here: the",
        "// alternative is code that compiles and throws.",
        "//",
        "// Narrow the ones that matter by hand — config, appEvents, ApiClient, Lit —",
        "// and leave the rest until their owning module earns a real shape.",
        "//",
        f"// Sources: {len(assigned)} names assigned to window across static/js.",
        "interface Window {",
    ]
    for name in on_window:
        lines.append(f"    {name}: any;")
    lines.append("}")
    lines.append(END)
    block = "\n".join(lines) + "\n"

    text = GLOBALS_DTS.read_text(encoding="utf-8")
    if START in text and END in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail.lstrip("\n")
    else:
        # first run: append the generated block
        text = text.rstrip("\n") + "\n\n" + block

    GLOBALS_DTS.write_text(text, encoding="utf-8", newline="")
    print(f"\nwrote {len(on_window)} members into {GLOBALS_DTS.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())